/*
*resourceDef.h
*
*/

#ifndef __RESOURCE_DEF_H__
#define	__RESOURCE_DEF_H__

#define	RECOGNITION_WINDOW_MENU_FUNC					"功能"
#define	RECOGNITION_WINDOW_ACT_CHINESE_SYMBOL_GEN		"中文字符生成"
#define RECOGNITION_WINDOW_ACT_SYMBOL_TRAIN				"字符训练"
#define RECOGNITION_WINDOW_ACT_ID_RECOGNITION			"身份证识别"

#define SYMBOL_GEN_WIDGET_LAB_DIR_OUT					"符号生成路径"
#define SYMBOL_GEN_WIDGET_BTN_DIR_OUT					"选择"
#define SYMBOL_GEN_WIDGET_BTN_GENERATOR					"生成"
#define SYMBOL_GEN_WIDGET_DIR_OUT_FILEDIALGO			"选择路径"
#endif // !__RESOURCE_DEF_H__
